### ISSUE TITLE
bug when trying to join a room

### ISSUE THREAD

**Issue by aliihsanyildizhan** [Animenosekai/jklmbot#1]
so after installing jklmbot and playwright I type this command python3.8 -m jklmbot --r ETTD and then it opens chromium but after 1 second of opening it closes itself and then gives me the following error code:                                                                                                                               

Error: strict mode violation: locator("iframe") resolved to 2 elements:
    1) <iframe width="256" height="60" scrolling="no" framebord…></iframe> aka locator("iframe[name=\"a-knhou0ht48x2\"]")
    2) <iframe></iframe> aka locator("iframe").nth(1)

=========================== logs ===========================

  checking visibility of frame_locator("iframe").locator(".joinRound")

============================================================                                                                                                      

help me fix this pls

**Comment by Animenosekai** [comment]
it's finally fixed !

There might be an issue with it trying to search for something that it doesn't find when joining a room and the script will only continue after 30 seconds but after that it should work fine.
